# Makefile for Exercise 1

FLAGS=-Wall

all: part1 part2 part3 part4

part1:
	gfortran $(FLAGS) -o part1 exercise1-1.f90
	
part2:
	gfortran $(FLAGS) -o part2 exercise1-2.f90
	
part3:
	gfortran $(FLAGS) -o part3 exercise1-3.f90
	
part4:
	gfortran $(FLAGS) -o part4 exercise1-4.f90

clean:
	rm -v part*
